apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-rdns
  namespace: kube-rdns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-rdns
    spec:
      containers:
      - name: kube-rdns
        image: niusmallnan/kube-rdns:v0.2.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9595
        env:
        - name: RANCHER_DEBUG
          valueFrom:
            configMapKeyRef:
              name: kube-rdns
              key: rdns.debug
        - name: RANCHER_ROOT_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: kube-rdns
              key: rdns.root_domain
        - name: RANCHER_BASE_RDNS_URL
          valueFrom:
            configMapKeyRef:
              name: kube-rdns
              key: rdns.base_url
        - name: RANCHER_RENEW_DURATION
          valueFrom:
            configMapKeyRef:
              name: kube-rdns
              key: rdns.renew_duration
        - name: RANCHER_INGRESS_RESYNC_DURATION
          valueFrom:
            configMapKeyRef:
              name: kube-rdns
              key: rdns.ingress_resync_duration
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9595
          initialDelaySeconds: 5
          timeoutSeconds: 1
